apiVersion: v1
kind: ServiceAccount
metadata:
  name: matterchat-app-sa
  namespace: matterchat
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-watcher
  namespace: matterchat
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: matterchat-job-watcher-binding
  namespace: matterchat
subjects:
  - kind: ServiceAccount
    name: matterchat-app-sa
    namespace: matterchat
roleRef:
  kind: Role
  name: job-watcher
  apiGroup: rbac.authorization.k8s.io
